### ISSUE TITLE
Actual IDE

### ISSUE THREAD

**Issue by edge0701** [openmv/openmv-ide#1]
Are you planning to release your current version of IDE open source? At the moment it just builds QT Creator, unless I am missing something? Just received my board and only find binaries...

**Comment by edge0701** [comment]
Ah. I found the current IDE in OpenMV/openmv/usr! Sorry about that!

**Comment by kwagyeman** [comment]
Um, that's the old IDE. The new IDE is here: https://github.com/openmv/openmv-ide

The new IDE is built on top of QtCreator. You have to use the openmv branch of the QtCreator repo.

https://github.com/openmv/qt-creator/tree/f6fe0d2f8c9a9b801a4ffa99927205ecdf20bf7b

Lots of stuff was modified in the code. All new changes are here: https://github.com/openmv/qt-creator/tree/f6fe0d2f8c9a9b801a4ffa99927205ecdf20bf7b/src/plugins/openmv

**Comment by edge0701** [comment]
I was on the wrong branch as I had pulled manually. All working.

Thanks for your help. And great work.
