### ISSUE TITLE
IDE hangs when using a new keyword

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv-ide#10]
The IDE hangs if you write a keyword which it doesn't know about.

How to repeat:

Load `HelloWorld.py` and write `test_mode=` inside snapshot (like it's a keyword arg):
``` img = sensor.snapshot(test_mode=)         # Take a picture and return the image.```
When you press `=` It hangs.

**Comment by kwagyeman** [comment]
Fixed.
