### ISSUE TITLE
Disable FW version check

### ISSUE THREAD

**Issue by frank26080115** [openmv/openmv-ide#102]
I'm developing on custom firmware from wayyyyyy back and the IDE keeps asking me to upgrade the firmware. Please add an option to stop this check. Thanks.

**Comment by kwagyeman** [comment]
I can add setting in the options dialog.

**Comment by kwagyeman** [comment]
There will be a do not show this dialog again checkbox on the upgrade dialog. The bottom right hand corner upgrade option will still exist.
