### ISSUE TITLE
Improve DFU window output.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv-ide#105]
![image](https://user-images.githubusercontent.com/4498013/105199275-45fdd200-5b47-11eb-95c7-e7da6cbdc535.png)

Please check if the line ends with "bytes\r" or "bytes\n" and if so, move the cursor to 0 instead of printing a new line, it will look much better.

EDIT:
2) Even better, check if it starts with the same word as the current line (Erase or Download) if Not, then print a new line...

3) If possible to keep all the output from the multiple DFU runs it would be nice.

**Comment by kwagyeman** [comment]
This is really hard to fix. If Arduino is paying for me to do then I will. The text arrives in an unbuffered manner. So, I will have to make a statemachine to parse it and determine where line ends are and etc.

E.g. I might receive half a line sometimes.

**Comment by iabdalkader** [comment]
I requested this because it will look much better. You only need to check for line ends and when you get a line end, scroll back to the beginning of the line, or if you keep a buffer for the line overwrite it. Points 2 and 3 are optional.

**Comment by kwagyeman** [comment]
Yeah, this is just a lot more involved that you think on the way the qplaintext edit works.

**Comment by kwagyeman** [comment]
This looks fine on apps line picotool. So, it's an issue with dfu-util. Won't fix.

**Comment by iabdalkader** [comment]
Same issue with picotool and bossac

**Comment by kwagyeman** [comment]
Fixed
