### ISSUE TITLE
Apply button in Options window is useless because Options window is modal

### ISSUE THREAD

**Issue by frank26080115** [openmv/openmv-ide#108]
IDE v 2.6.9

The Options window is modal. There's no point in having a Apply button if the window is modal because I can't edit the code while the window is open, it forces the user to click OK 100% of the time anyways so the Apply button is useless

I think the Options window should not be modal. It'd be nice to test out settings quickly.

**Comment by kwagyeman** [comment]
This is how QtCreator works internally. I don't want to change this since there's a lock that goes into place when the options dialog is opened.
