### ISSUE TITLE
feature request: revert handling of missing file back to how it used to work

### ISSUE THREAD

**Issue by frank26080115** [openmv/openmv-ide#110]
The new v 2.6.9 IDE has started to immediately tell me when an open file no-longer exists. Which is pretty often since I'm unplugging the OpenMV all the time.

Previous versions of the IDE did not do any notifications at all, but upon attempting to save, it would claim it was read-only with a very elegant bar below the file name

The new version will force you to choose between closing the file or saving it somewhere else with a dialog

I much prefer the older way since I will be plugging the OpenMV back anyways later

I feel like editing files on the microSD card or internal flash would be a common enough use-case to justify my preference for many users. I know the IDE serves the currently-open file via REPL stdin, but I don't think it does any drive-mirroring or JIT mpy-cross compiling, so it makes sense for a user to have a ton of code files open in the IDE that are actually saved directly in flash or SD card, which makes sure that the latest code is in flash. This will be true for any project with more than one file. Forcing people to either close or move them whenever the OpenMV is unplugged is super annoying.

If you insist on notifying the user with a dialog box, try the way Notepad++ handles the same situation. The user has the option of just letting the file stay open.

If there's a difference between the file in flash vs in the editor when the OpenMV is re-plugged-in, then the editor usually asks if the user wants the copy on the device or the copy on the screen.

**Comment by kwagyeman** [comment]
Hi, I didn't change the IDE logic on this. So, I don't know what's going on.

@iabdalkader - Did the way the camera writes data to the SD card change in the latest firmware? I think write. Maybe it's causing this?

**Comment by iabdalkader** [comment]
The IDE has always been like that, this is 2.6.8

![image](https://user-images.githubusercontent.com/4498013/107075681-1c090880-67f3-11eb-938c-0a3aa7edcc21.png)

Nothing in the firmware could affect this.

**Comment by iabdalkader** [comment]
Maybe add a checkbox "Don't show this message again"

**Comment by frank26080115** [comment]
![Screenshot 2021-02-05 110649](https://user-images.githubusercontent.com/1427911/107077853-4e3e4a00-67a2-11eb-92b5-f021e226b9a2.png)

That's v 2.5.1

Adding a checkbox doesn't help avoid the problem. The problem is that the user is now either forced to lose the file or to move it. Losing the file is bad, moving the file adds risk that the user forgets which file has the latest changes. The proposed solution is to keep it in-memory, not on disk, and just hope the user plugs the back the OpenMV.

**Comment by iabdalkader** [comment]
I see the issue, but I really don't think it has anything to do with the firmware... I think it's core qt creator functionality that may have changed with an update.

**Comment by frank26080115** [comment]
This has nothing to do with firmware, sorry for the confusion but when I said flash, I meant the flash file system, not firmware.

**Comment by kwagyeman** [comment]
What OS are you on? Linux/Windows has not changed here. Only Mac Qt was updated.

**Comment by frank26080115** [comment]
Windows 10 thanks

**Comment by kwagyeman** [comment]
Behavior seems to be back to what you wanted.

So, I will not do anything.

![image](https://github.com/openmv/openmv-ide/assets/5694981/919a8076-7e45-4a1a-9261-4021ae098869)

Note that the file syncing system now works in the IDE. So, you should edit code in your Documents folder. The IDE will automatically scan your import list when you run code and it will update the files on the camera if it sees the version on the camera are different that what's on the PC.
