### ISSUE TITLE
Docs update

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv-ide#115]
replaced `sensor.set_vsync_output` with `sensor.set_vsync_callback`
sensor.set_vsync_callback accepts a callback function that takes 1 arg, VSYNC state:
Example usage:
```
led_pin = Pin('LED_BLUE', Pin.OUT_PP, Pin.PULL_NONE)
sensor.set_vsync_callback(lambda state, led=led_pin: led_pin.value(state))
```

If callback is None, the VSYNC interrupt is disabled.

**Comment by kwagyeman** [comment]
Done
