### ISSUE TITLE
Camera's device name is given by USB plug insertion order

### ISSUE THREAD

**Issue by alberto-grl** [openmv/openmv-ide#119]
When using multiple cameras it is not possible to tell which one is associated with a ttyACM* device, at least in Linux.
See https://forums.openmv.io/t/openmv-ide-change-camera-name/5697/5

Did a pull request with a sub-optimal solution.

**Comment by kwagyeman** [comment]
Will resolve in another IDE release.

**Comment by kwagyeman** [comment]
Added to IDE.

Pass -list_ports to list ports
Pass -serial_number_filter <serial_number> for the -list_ports to filter to one serial port.
