### ISSUE TITLE
"save open script to openMV camera" sends script to wrong microSD card

### ISSUE THREAD

**Issue by kdarras** [openmv/openmv-ide#123]
On Ubuntu 20.04, when I plug a microSD card into my laptop directly, and I also connect a H7+ board to interact with it through the IDE, the currently active script is saved to the SD card that is inside the laptop (instead of the openMV cam) when clicking the button "Tools> save open script to openMV cam (as main.py)"

**Comment by kwagyeman** [comment]
Hi, the IDE can't really tell which disk is which. It looks for a FAT disk with the .openmv_disk file onboard. If you have two such disks then it just picks the first one it finds.

You can change the association by click on the disk label in the IDE and selecting the right disk. The IDE will remember this.
