### ISSUE TITLE
Handle HiDPI displays on Linux.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv-ide#125]
The default IDE scale is too small for HiDPI displays, I use a workaround for this issue but not everyone knows how to fix it:
Example: https://forums.openmv.io/t/wifi-examples-in-documentation/6072/5 

The IDE should somehow detect HiDPI and scale accordingly or if there's a setting in QT to handle this it should be enabled.

Hint: Search for QT_SCALE_FACTOR

And https://doc.qt.io/qt-5/highdpi.html

**Comment by kwagyeman** [comment]
Enabled this for linux.
