### ISSUE TITLE
The neural network file for number recognition cannot be found in OpenMV Ide2.6.9

### ISSUE THREAD

**Issue by D-Twelve-T** [openmv/openmv-ide#126]
Hello, I want to realize the task of identifying two digits of numbers, calculating the median, and sending the signal to STM32 microcontroller. I downloaded the IDE of 2.6.9, but I could not find the NN. Lenet neural network file in the CNN model network, and I could not find the relevant neural network file in the IDE folder either. May I ask how to solve this? Where can I find this neural network file to recognize numbers? I need him to tell me what the number is. Please help me,pelase. Thanks❗

**Comment by kwagyeman** [comment]
Hi, this was removed. We switched to TensorFlow. You can create your own CNNs now.

**Comment by W3en2g** [comment]
can we create our own CNN with openmv 4?

**Comment by kwagyeman** [comment]
Yes
