### ISSUE TITLE
Tabs need some improvments.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv-ide#127]
* The following common shortcuts/hotkeys should be used:

Ctrl + Page Up/Down -> Switch to the left or right tab.
Ctrl + Shit + Page Up/Down -> Move the tab itself to the left or right.
Ctrl + T -> open new tab (with new script)
Ctrl + W -> close the current tab.
Ctrl + Shift + T -> re-open the most recently closed tab

* The drop down list is not needed anymore, in fact it's confusing to have both. 

* Finally, the tabs should be on the same bar where the drop-down list is/used to be, and the new bar should be remove. For example:
![image](https://user-images.githubusercontent.com/4498013/127884461-a1d69ca6-9803-44c1-a1ef-40471e9b5a81.png)

**Comment by kwagyeman** [comment]
Ctrl + Page Up/Down -> Switch to the left or right tab. (fixed)
Ctrl + Shit + Page Up/Down -> Move the tab itself to the left or right. (fixed)
Ctrl + T -> open new tab (with new script) -> use ctrl+N.
Ctrl + W -> close the current tab. (this is already implemented)
Ctrl + Shift + T -> re-open the most recently closed tab (qt-creator editor manager doesn't store this history)

The drop down list is not needed anymore, in fact it's confusing to have both. -> Punt to next-release/Won't fix
Finally, the tabs should be on the same bar where the drop-down list is/used to be, and the new bar should be remove. For example: -> Punt to next-release/Won't fix

**Comment by iabdalkader** [comment]
> The drop down list is not needed anymore, in fact it's confusing to have both. -> Punt to next-release/Won't fix
> Finally, the tabs should be on the same bar where the drop-down list is/used to be, and the new bar should be remove. For example: -> Punt to next-release/Won't fix

Should keep this open then.

**Comment by iabdalkader** [comment]
The Ctrl + Page Up/Down are swapped, page up should go to left tab, page down should go to right tab.

**Comment by kwagyeman** [comment]
Fixed
