### ISSUE TITLE
Add hotkey to reload firmware.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv-ide#128]
Would save a lot of time when testing small changes a lot, it should use the most recently used path and skip the "Tool->Run Bootloader->Run dialog" I suggest ctrl+shit+L

**Comment by kwagyeman** [comment]
This is rather dangerous issue for users to accidentally activate. But, okay, not that hard. But, it still takes quite a bit of time to load firmware. I don't see the need for this... as you're still waiting for the firmware load. Will leave the issue open.

**Comment by iabdalkader** [comment]
That's why it's a longer key combination (ctrl + shit + l), and it's useful because it saves the time needed to go through the bootloader dialog. These small things add up when you load fw 10s of times in a row.

**Comment by iabdalkader** [comment]
Alternatively, the shortcut could show up the "run bootloader" dialog with run button having focus.

**Comment by kwagyeman** [comment]
Ctrl + Shift + L -> launches Run Bootloader Dialog
Ctrl + Shift + E -> Launches Erase Flash Disk Dialog
