### ISSUE TITLE
AltGr misbehaving on OpenMV IDE 2.8.1

### ISSUE THREAD

**Issue by fickludd** [openmv/openmv-ide#129]
I just upgraded to IDE 2.8.1 (tabs, yey). However this seems to have broken keyboard input. I’m on a Swedish keyboard layout, where {} brackets are on AltGr-7 to AltGr-0. Nothing happens when I try to input these. This is quite annoying, fix would be nice :).

**Comment by falthaus** [comment]
Same here: IDE 2.8.1 on Windows 10 Home with a Swiss keyboard layout and on two different computers.
- [AltGr]+[0..9] get ignored, so do [Ctrl]+[Alt]+[0..9] (which should have the same effect)
- [AltGr]+[e] would work (on the Swiss keyboard that's the Euro sign - obviously not needed for python, but it seems some [AltGr] stuff seems to work)
- I only have this issue with OpenMV IDE, so I guess it's not on Windows this time.
- it doesn't matter what Language I set in Options->User Interface->Language

[AltGr]+[3] is the '#' sign, so commenting is a bit difficult now...

**Comment by kwagyeman** [comment]
Hi, tab shortcuts are generated by:

QStringLiteral("Ctrl+Alt+%1");

Where %1 is replaced with 1 through 0.

What should I replace this with? I can remove the feature. Would like to keep it. But, I don't know if that's possible.

**Comment by kwagyeman** [comment]
Also, what OS are you both using? I will cut a new release quickly with the fix.

**Comment by fickludd** [comment]
I'm on Win 10 Pro. I would

  1) remove the shortcut by default, because the downside is quite bad for affected users
  2) think about adding these shortcuts under configuration option, so users like yourself can benefit from the shortcuts 
  3) (bigger job) add system for configuring shortcuts, because everyone has different preferences, and this is not going to be the last time they conflict. It's also very convenient to be able to configure the same shortcuts in OpenMV IDE as I might have in other IDEs.

**Comment by kwagyeman** [comment]
QtCreator actually already has #3. I just hid it. I'll renable it and turn the shortcut off by default.

To note, part of the goal with OpenMV IDE was not to make it have so many options that it becomes overwhelming like most IDEs.

**Comment by fickludd** [comment]
Great!

Yeah I think you're keeping a small but good feature-set in general. The only features I really miss from e.g. IntelliJ is `goto definition/usage` and `breadcrumbs` (meaning goto previous/next cursor location).

**Comment by kwagyeman** [comment]
The IDE has goto previous location. But, I hid it too. I can re-enable.

**Comment by kwagyeman** [comment]
Make a bug ticket for these features.

**Comment by kwagyeman** [comment]
Just disabled these QStringLiteral("Ctrl+Alt+%1"); shortcuts.
