### ISSUE TITLE
Issue flashing OpenMV firmware on arduino nano 33 ble sense

### ISSUE THREAD

**Issue by hugoferrero** [openmv/openmv-ide#133]
Hi. i'm trying to install the openmv firmware on my board, but the ide doesn't recognize the bootloader update and the "softdevice" on my board...any ideas?. I took some prints. Thanks in advanced. Regards.
![Captura de pantalla de 2021-10-24 19-05-32](https://user-images.githubusercontent.com/34080955/138616218-7fe0f7dd-d480-4617-8480-e3a1cc8d23b0.png)
![Captura de pantalla de 2021-10-24 19-56-17](https://user-images.githubusercontent.com/34080955/138616283-3e8f1020-80e3-4a2b-958d-37d576e7d53e.png)
![Captura de pantalla de 2021-10-24 19-05-54](https://user-images.githubusercontent.com/34080955/138616288-395c041f-d97b-4b2e-8a3d-cca872792b43.png)

**Comment by kwagyeman** [comment]
You have to select the option when flashing the bootloader with Arduino to install OpenMV support.
