### ISSUE TITLE
Can´t flash OpenMV firmware on arduino nano ble 33 sense 

### ISSUE THREAD

**Issue by hugoferrero** [openmv/openmv-ide#134]
..as the title says i can´t flash OpenMV firmware. I'm  going to describe the steps i'm doing:

1 - Installed the latest version of  "Arduino Mbed OS Nano Boards" which is 2.5.2.

2 - Uploaded the scketch  "Nano33_updataBLandSoftDevice".

3 - Opened  monitor serie to install Soft device:
![Captura de pantalla de 2021-10-26 21-22-47](https://user-images.githubusercontent.com/34080955/138979544-a612e80b-ee2e-45a9-9b0e-db860c135739.png)

4 - After completion, the board  enter the bootloader mode:
![Captura de pantalla de 2021-10-26 21-22-25](https://user-images.githubusercontent.com/34080955/138979802-c98d232e-d046-4cd8-a1fd-e33d0158446a.png)

5 - Opened OpenMV IDE and tried to install the firmware:

![Captura de pantalla de 2021-10-26 21-33-49](https://user-images.githubusercontent.com/34080955/138980330-ed13236e-5b9f-454d-b5c2-fd5f8732e04e.png)

![Captura de pantalla de 2021-10-26 21-28-52](https://user-images.githubusercontent.com/34080955/138979978-ad2f7b1e-a6bb-4e85-9c2a-f49e405b501e.png)

 The IDE doesn't recognize the bootloader. The message says that i have to update the bootloader and install SoftDevice.

I'm following this tutorial:
https://docs.arduino.cc/tutorials/nano-33-ble/getting-started-omv

FYI: sometimes, in monitor serie, after complete flashing, it asks me again if i want to install soft device.

thanks in advance.

**Comment by kwagyeman** [comment]
Hi, looking at fixing this now. But, I can't reproduce... Mine works as expected.

**Comment by rekk2** [comment]
having this issue as well with nano 33 ble sense.  Using windows, arduino ide 1.8.19, openmv 2.9
![Clipboard02](https://user-images.githubusercontent.com/32183761/166948167-8ded3eee-3a8e-45f8-9ccf-a26b4d59486f.jpg)
![Clipboard01](https://user-images.githubusercontent.com/32183761/166948354-e2b82522-df8f-4e19-9b64-7fb03df5bace.jpg)

**Comment by kwagyeman** [comment]
Hi, you are using our Open Terminal feature there which doesn't run our bootloader... So... what exactly are you doing?

Like, the text you have in the terminal is NOT generated by the IDE.

**Comment by rekk2** [comment]
I'm following this guide
https://docs.arduino.cc/tutorials/nano-33-ble/getting-started-omv and the
arduino serial monitor showed the same stuff the other guy had.  And the
terminal also shows roughly the same thing with the y/n question

**Comment by kwagyeman** [comment]
Yeah... but, something you did went wrong. Do you see how the serial terminal has a black background versus a white one?

You are literally running the bootloader that Arduino flashed onto the BLE 33 right now. Not our OpenMV IDE bootloader.

The steps from Arduino are correct.

**Comment by kwagyeman** [comment]
Actually, now I see it... both of you used the Open Terminal feature and then are re-running the script flashed on the board.

...

So, I'm going to close this issue as user error.
