### ISSUE TITLE
Crash when flashing OpenMV firmware on arduino nano ble 33

### ISSUE THREAD

**Issue by Joymaker** [openmv/openmv-ide#135]
Very much like #134 except that, at the critical moment, OpenMV IDE crashes. 
Using OpenMV IDE to follow these instructions: https://docs.arduino.cc/tutorials/nano-33-ble/getting-started-omv

Crashed with the MacOS crash report attached.  MacOS Big Sur 11.6, OpenMV IDE 2.8. Below is pictured the situation just before I pressed the okay button, which led to an instant crash.
<img width="1273" alt="OpenMV before crash" src="https://user-images.githubusercontent.com/5916231/142649198-c147298c-f394-4c62-84ac-903d0a58f2aa.png">

[New bootloader softdevice log.txt](https://github.com/openmv/openmv-ide/files/7571250/New.bootloader.softdevice.log.txt)

[Second crash log.txt](https://github.com/openmv/openmv-ide/files/7571254/Second.crash.log.txt)

**Comment by kwagyeman** [comment]
Hi, looking at fixing this now. But, I can't reproduce... Mine works as expected.

**Comment by kwagyeman** [comment]
Found why this crashes the IDE. Fixed.

**Comment by OKPersson** [comment]
This issue persists on version 2.9.2 on macOS 12.4 Monterey, Thought it was due to the softdevice or bootloader of the nano33 BLE sense, but after a reflash via the arduino ide it's still not working.
