### ISSUE TITLE
Enlarging preview pane makes bottom bar disappear

### ISSUE THREAD

**Issue by kdarras** [openmv/openmv-ide#142]
When enlarging the image preview pane vertically, in such a way that it hides the histograms, the bottom bar (which displays the serial terminal button, firmware version, etc.) disappears outside of the screen frame:
![image](https://user-images.githubusercontent.com/7696198/156526319-81f45ebe-ef43-44c4-9883-84d7fc929616.png)

This behavior was consistently observed on a laptop running Ubuntu 20.04 with a Full HD resolution screen, as well as a WIndows laptop with similar resolution. Interestingly when capturing the current window frame with the built-in screenshot app, the entire window will be captured.

**Comment by kwagyeman** [comment]
I have to update the IDE framework to fix this. It's due to scaling issues.

Will fix.

**Comment by kdarras** [comment]
This is fixed in the new IDE, thanks!

**Comment by kdarras** [comment]
Unfortunately, this issue was either solved only on my larger screen display or it was re-broken with the latest update... can't remember.
In any case, the issue remains on 2.9.0 on Ubuntu 20.04.4 LTS at present. THis is my whole screen:
![image](https://user-images.githubusercontent.com/7696198/164615938-c13ed56e-6304-40c6-87a5-6ca3bff3e13e.png)

**Comment by kwagyeman** [comment]
Hi, I have to update the IDE qt version to fix this. I will get this done soon.

**Comment by kwagyeman** [comment]
Ibrahim confirmed this is fixed with the latest IDE. Which will be released hopefully next week.
