### ISSUE TITLE
 Nano RP2040 Connect Micropython MLC example OSError: [Errno 2] ENOENT

### ISSUE THREAD

**Issue by jomoengineer** [openmv/openmv-ide#145]
**Describe the bug**
When running the LSM6DSOX IMU MLC example, lsm6dsox_mlc.py, there is a message stating that it may be required to copy lsm6dsox to the RP2040 to run the example and when doing so, the script fails with the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "lsm6dsox.py", line 136, in __init__
  File "lsm6dsox.py", line 189, in load_mlc
OSError: [Errno 2] ENOENT
MPY: soft reboot
MicroPython: v1.17-omv-r22 OpenMV: v4.2.3 HAL: v1.3.0 BOARD: Arduino Nano RP2040 Connect-RP2040
Type "help()" for more information.
>>> 
```

If I remove the lsm6dsox.py window from the OpenMV IDE screen, the example seems to run without issue.
It appears the wrong file is being copied to the RP2040 for this example.

**To Reproduce**
1. Go to OpenMV IDE with the Nano RP2040 Connected connected, 
2. Click on File->Examples->Arduino->Nano RP2040->Sensors->
3. Scroll down to lsm6dsox_mlc.py
4. Run the script
5. An Import Helper - OpenMV IDE pop-up window will appear stating:
    Module "lsm6dsox" may be required to run your script
6. Click Yes and the file lsm6dsox.py is copied to the board
7. The error will be seen once the script runs
     NOTE: This appears to only occur the first time the script is run after a firmware install.
                The script seems to run as expected on subsequent tries.

**Expected behavior**
No error seen during starting of script and a prompt in the Serial Terminal showing "MLC Configured..." should appear. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10980402/156499533-f776c7e4-6841-4863-8c32-bf201de49792.png)

**Please complete the following information**
 - IDE version: 2.9.0
 - Firmware version: 4.2.3
 - Board: Arduino Nano RP2040 Connect
 - OS: Windows 10

**Comment by iabdalkader** [comment]
This is bug in the IDE, it copies the example script called `lsm6dsox.py` instead of copying the library `lsm6dsox.py`. The workaround is:
* Download the library https://raw.githubusercontent.com/openmv/openmv/master/scripts/libraries/lsm6dsox.py
* Copy to storage and safe remove, restart the board
* Connect, the IDE will ask you to update it (because it's different from the local file) click No
* The example should work (note you also need a model, see comments/links the example).

**Comment by kwagyeman** [comment]
Ibrahim, please rename the example script in our repo. I will then update the examples with the new firmware release.

**Comment by iabdalkader** [comment]
I can rename it, but the issue is it's copying the example not the library from `libraries`.

**Comment by jomoengineer** [comment]
@iabdalkader 
Yes, I forgot to add the step for the model but I did find it and run it.

Initially I downloaded the lsm6dsox.py lib from the following MicroPython link since I was not able to find it elsewhere.
Note: They call the basic lsm6dsox example lsm6dsox_basic.py.  The way it is listed in OpenMV IDE both the lib code and the example are the same name. 
[https://github.com/micropython/micropython/tree/master/drivers/lsm6dsox](url)

Perhaps this is why the example started to work.

Also, there is a second pop-up that appears after it asks to download an update to the lsm6dsox.py on the board which asks if the user want to update the file on the PC. 
![image](https://user-images.githubusercontent.com/10980402/156626496-ae8d7716-e147-4099-a494-72829b8d0a85.png)


 If I do this with the lsm6dsox.py lib code on the board, and then restart the IDE, I do not see the request to download the file to board or the error.

**Comment by iabdalkader** [comment]
Renamed the example to `lsm6dsox_basic.py`

**Comment by jomoengineer** [comment]
I renamed the lsm6dsox.py example to lsm6dsox_basic.py under the 'share\qtcreator\examples\Arduino\Nano-RP2040\01-Sensors' OpenMV IDE folder, and then:
 1. Started OpenMV IDE
 2. Connected to the Rp2040
 3. Reflashed the FW on the RP2040 from the IDE including erasing the internal mem
 4. Safe Removed and re inserted the RP2040 USB cable
 5. Copied the lsm6dsox_vibration_monitoring.ucf model file to the RP2040
 6. Reran the lsm6dsox_mlc.py example and had the IDE copy the lsm6dsox driver to the RP2040.
 7. This did result in what looks like the driver code being copied to the board but did result in an error in the IDE:
 
 ```
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "lsm6dsox.py", line 136, in __init__
  File "lsm6dsox.py", line 189, in load_mlc
OSError: [Errno 2] ENOENT
MPY: soft reboot
MicroPython: v1.17-omv-r22 OpenMV: v4.2.3 HAL: v1.3.0 BOARD: Arduino Nano RP2040 Connect-RP2040
Type "help()" for more information.
>>> 
```
 It stops at the following code from line 129 in lsm6dsox.py file from the board

```
	def read_accel(self):
		mv = memoryview(self.scratch_int)
		f = self.accel_scale
		self.i2c.readfrom_mem_into(self.address, _OUTX_L_XL, mv)
		return (mv[0] / f, mv[1] / f, mv[2] / f)

```

If I click on the lsm6dsox_mlc.py example window in the IDE and run it again, it seems to work just fine.

It does prove that the correct lsm6dsox.py driver does get copied to the board with the lsm6dsox.py example named lsm6dsox_basic.py.

**Comment by iabdalkader** [comment]
Thanks for testing! I already renamed it in the other repo, and this should be fixed in the next update. FYI after copying a file to the storage, you need to reset the cam. The IDE should probably mention that.

**Comment by jomoengineer** [comment]
Yeah, it just ran and produced the error after I clicked ok to copy the file to the board.  It did not stop the run process after copying the file.

**Comment by iabdalkader** [comment]
This one needs to be fixed @kwagyeman. The cam doesn't see new files before a reset, maybe force a reset ?

**Comment by iabdalkader** [comment]
You know actually I just realized that this library is already built-in (frozen) in the Nano RP2040 firmware, the IDE just needs to learn that and ignore copying it. You shouldn't need to copy it to the file system at all.

**Comment by kwagyeman** [comment]
Yeah, the IDE won't ask unless you name an example the same as a library.

**Comment by iabdalkader** [comment]
It's true, it does not ask to copy. I guess this issue is fixed.
