### ISSUE TITLE
my macbook cannot open the ide

### ISSUE THREAD

**Issue by a2244144844** [openmv/openmv-ide#146]
There's a warning,  please close any other apps writing/reading the data of ide and  re-open it later. 
I will be very appreciated if you can tell me the reason. 
I just downloaded it for a while and never open it before.

**Comment by kwagyeman** [comment]
It's because your settings directory (~/.config) is owned by root and the IDE can't access it. You need to fix this on your file system. Please do the necessary chown/chgroup commands. Or launch the IDE with sudo.

**Comment by a2244144844** [comment]
Thanks a lot! The problem is solved.
