### ISSUE TITLE
Portenta load firmware fails.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv-ide#147]
On Linux, even though the board resets to DFU.

![image](https://user-images.githubusercontent.com/4498013/157504840-8b61a283-e87e-4825-9bd3-4f78cf28e5f8.png)

**Comment by kwagyeman** [comment]
This happens because the PID/VIDs are screwed up that the board is returning. For example, I can confirm on the Nicla that it has the PID 035f in application mode which is the bootloader PID.

**Comment by kwagyeman** [comment]
I will add the bootloader PID to the list of PIDs that the IDE will accept... however, this isn't really right.

**Comment by kwagyeman** [comment]
Wait, no, this is correct.

**Comment by iabdalkader** [comment]
> I will add the bootloader PID to the list of PIDs that the IDE will accept...

If you run it again it works. I think it just needs to wait longer or poll to account for different USB hubs/controllers timing.

**Comment by kwagyeman** [comment]
No, I dumped the PID our firmware exposes and it's the wrong one. We might want to fix this.

When rebooting to the bootloader I cache the PID of when it was in app mode. The code expects to see the app mode PID when looking up what to do and I have the bootloader PID.

**Comment by iabdalkader** [comment]
Note the Portenta and NiclaV have different bootloader PIDs...So is this issue fixed or not ? I sent you a list of PIDs that includes the bootloaders.

**Comment by kwagyeman** [comment]
Yes

**Comment by iabdalkader** [comment]
This issue is not fixed in 2.9.1

**Comment by iabdalkader** [comment]
Fixed in 2.9.2
