### ISSUE TITLE
Tab bar disappears under certain conditions.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv-ide#149]
* Run the IDE. By default it opens `helloworld_1.py`
* Make any change to this script **without saving** (for example delete any line)
* Close the script by clicking the **X on the script tab**.
* The IDE shows the dialog that asks to save changes.
* Press the keyboard escape key or click on dialog's Cancel button (do Not click "Do not save").
* The tab bar disappears:
![image](https://user-images.githubusercontent.com/4498013/157728432-2f99b00a-8704-4f24-b72f-0504d8fd5ca2.png)

**Comment by kwagyeman** [comment]
This is normal. The Tab bar disappears when no scripts are open. It will reappear when you open a script.

**Comment by kwagyeman** [comment]
I don't see a bug here. Just tested it out.

**Comment by iabdalkader** [comment]
> The Tab bar disappears when no scripts are open

But the script is still open.

![image](https://user-images.githubusercontent.com/4498013/165032259-d9fa6f22-fac3-4fd6-9124-4a9bab15387b.png)

The script was never closed, I just cancel the close dialog.

**Comment by kwagyeman** [comment]
I see the issue now. I clicked accept.

**Comment by kwagyeman** [comment]
Found the issue, fixed it.

**Comment by iabdalkader** [comment]
> I see the issue now. I clicked accept.

That's why I was very specific about the steps :smiling_face_with_tear:

**Comment by iabdalkader** [comment]
Related issues: Unchanged tab closes together with unsaved tab, and the bar still disappears under certain conditions.

### Please take the time to read and follow the steps carefully to reproduce these issues:

* Start the IDE (by default it opens `helloworld_1.py`)
* Create 2 new scripts (hit Ctrl+n twice).
* Now you have 3 open scripts: `helloworld_1.py`, `untitled_1.py` and `untitled_2.py`
* Make any change to the **second script** `untitled_1.py` (i.e the one before the last open script).
* Close that script (`untitled_1.py`) by clicking the **X on the script tab**.
* The save script popup dialog shows up, click on the **"Do not save"** button.
#### First bug -> the last two tabs are closed (`untitled_1.py` and `untitled_2.py`).

* Next close the remaining `hellowrld_1.py` script by clicking the **X on the script tab**.
#### Second bug -> script is closed, but tab bar disappears and `untitled_2.py` comes back again.

**Comment by kwagyeman** [comment]
Is this with the new version of the compiled IDE?

**Comment by iabdalkader** [comment]
Yes, 2.9.1

**Comment by kwagyeman** [comment]
Found the bug. Code was calling itself twice.

**Comment by iabdalkader** [comment]
Fixed.
