### ISSUE TITLE
wifi programming port used

### ISSUE THREAD

**Issue by goyzhang** [openmv/openmv-ide#15]
Hello,
I just got my new openmv. After installing the IDE and run it, it indicated that: "Another application is using hte OpenMV Cam broadcast discovery Port. Please close that application and restart OpenMV IDE to enable WiFi programming. "

Ok, I got it. But I need to know which port you want to in order to fix it. Any idea?

**Comment by kwagyeman** [comment]
Oh, wow, this feature is not in use yet... Um, we don't have wifi programming support yet so please ignore this.

The port is ABD1.

**Comment by goyzhang** [comment]
I see, thank you.  BTW what did you mean by ABD1, shouldn't that be a ipv4 port number?

**Comment by kwagyeman** [comment]
#define OPENMVCAM_BROADCAST_PORT 0xABD1

It's a UDP broadcast port we bind to that the OpenMV Cam will send broadcast UDP packets on. WiFi programming hasn't been completed yet. However, we've basically got the infrastructure for it. Random other things have been delaying it's implementation...

That said, we're going to release soon, maybe I'll do this right afterwards. I've been itching to add some big features...
