### ISSUE TITLE
dfu-util exit code 74: openmv.dfu not found

### ISSUE THREAD

**Issue by kdarras** [openmv/openmv-ide#154]
I have a bricked H7+ board and I need to reset it. I got to the point where I have to connect a jumper wire between the BOOT and RST pins, connect the camera (no LEDs turned on, how do I know " when DFU has finished enumerating" ?), and then press OK.
Then I got the error code:

```
/home/kdarras/openmvide/share/qtcreator/dfu-util/linux64/dfu-util -w -d ,0483:df11 -a 0 -s :leave -D /home/kdarras/.config/OpenMV/qtcreator/firmware/OPENMV4P/openmv.dfu

dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2020 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/


dfu-util: Could not open file /home/kdarras/.config/OpenMV/qtcreator/firmware/OPENMV4P/openmv.dfu for reading: No such file or directory
```

However, since indeed the file openmv.dfu is not in that directory, I did not report it to the DFU-util team, as it is missing in the openMV IDE.

In the meantime, could that missing file ne sent so I can fix my H7+ board?

**Comment by kwagyeman** [comment]
DFU doesn't work on that board. You have to upload the bootloader.DFU using the Run Bootloader Tool in the IDE for the OPENMV4P board. Then you can use our regular bootloader to load the board.

You cannot try to load the whole firmware with DFU. It will not work. ST changed the firmware on the silicon which makes the tool unable to flash more than 1 sector.
