### ISSUE TITLE
Install the latest dev release feature is broken on new OSes.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv-ide#155]
Test on any recent system.

![image](https://user-images.githubusercontent.com/4498013/170862325-4966817c-ee6b-4a5e-ac1f-a6806f2bb574.png)

**Comment by kwagyeman** [comment]
This is fixed for version 4.0.0 with new SSL.

**Comment by kwagyeman** [comment]
Ibrahim confirmed fixed.
