### ISSUE TITLE
Arduino nano ble 33 sense not found by openMV

### ISSUE THREAD

**Issue by bendawsonfuse** [openmv/openmv-ide#158]
Hi there,

I'm trying to connect my Arduino nano 33 ble sense with openMV, and I'm following the Arduino webpage instructions here:
https://docs.arduino.cc/tutorials/nano-33-ble-sense/getting-started-omv#troubleshoot
I successfully flash the openMV firmware and then the BOSSAC firmware is successfully updated. But then openMV just doesn't recognise that I have the board connected. Here are some screenshots of the messages I am getting.

Installing latest Bossac firmware:
![image](https://user-images.githubusercontent.com/108734297/177319569-ca96d038-a36d-4f55-a3cd-332bd9be4f18.png)

Update complete:
![image](https://user-images.githubusercontent.com/108734297/177319630-20b176a9-29d6-4ec3-99e8-bf32eb06df93.png)

then when I click ok (and I have waited over half an hour for any lights on the board to change as suggested), i get this message:
![image](https://user-images.githubusercontent.com/108734297/177319736-9d2c2e20-27b9-4c85-86ae-12f1313ac0be.png)

Which then asks me if my device is bricked, and then follows with this:
![image](https://user-images.githubusercontent.com/108734297/177319884-ff635fdb-2910-493e-9b23-50a02c450b93.png)

Any help is appreciated,
Thanks

**Comment by kwagyeman** [comment]
Hi, this is an issue folks have encountered when using the wrong bootloader firmware on the BLE device. You need to follow Arduino's instructions to load their custom OpenMV firmware bootloader so our firmware update sticks.
