### ISSUE TITLE
TypeError: must be str, not NoneType

### ISSUE THREAD

**Issue by jiapei100** [openmv/openmv-ide#16]
> $ ./make.py 
> Traceback (most recent call last):
>   File "./make.py", line 253, in <module>
>     make()
>   File "./make.py", line 228, in make
>     " && make installer INSTALL_ROOT="+installdir + " IFW_PATH="+ifdir):
> TypeError: must be str, not NoneType

**Comment by kwagyeman** [comment]
Mind sending a PR to fix the issue?
