### ISSUE TITLE
The command "picotool" terminated with exit code 249

### ISSUE THREAD

**Issue by 6ffm70** [openmv/openmv-ide#160]
I have a brandnew Arduino Nano RP2040, and I want to flash the firmware, so I can use micropython. That doesn't work, it stops with the error message 
```
PicoTool firmware update failed!

The command "picotool" terminated with exit code 249

DETAILS
/home/6ffm70/etc/OpenMV_inst/share/qtcreator/picotool/linux64/picotool load -x /home/6ffm70/.config/OpenMV/qtcreator/firmware/ARDUINO_NANO_RP2040_CONNECT/firmware.bin

No accessible RP2040 devices in BOOTSEL mode were found.

but:

Device at bus 1, address 30 appears to be a RP2040 device in BOOTSEL mode, but picotool was unable to connect
```

I'm using this guide:
https://docs.arduino.cc/tutorials/nano-rp2040-connect/rp2040-openmv-setup

My environment: Ubuntu 20.04 on a Lenovo laptop; OpenMV IDE 2.9.2

What happens?
I start the IDE, 
![image](https://user-images.githubusercontent.com/50849255/179174183-3d857c68-99dc-4078-b2ae-73273d37a26e.png)
connect the Arduino with a microUSB cable (tried several different), 
![image](https://user-images.githubusercontent.com/50849255/179174294-388e34f3-a50e-4097-9749-f342897dee65.png)
press the boot button on the Arduino twice (now the LED is constantly green, the computer recognizes a mass storage device)
![image](https://user-images.githubusercontent.com/50849255/179174183-3d857c68-99dc-4078-b2ae-73273d37a26e.png)
I press connect, a window appears as per manual
![image](https://user-images.githubusercontent.com/50849255/179174809-0c36b9f5-1cbf-4a85-96b6-c96fa2f2a89e.png)
I press OK, above error meassage appears.

Is there a workaround to not use OpenMV? Can I drag and drop ARDUINO_NANO_RP2040_CONNECT/firmware.bin via my file browser?

**Comment by kwagyeman** [comment]
Hi, this isn't OpenMV IDE specific. It's some issue with the PicoTool on your PC. You'll need to ask the RPi folks why their tool is throwing this error.
