### ISSUE TITLE
No cursor on terminal spawned from IDE

### ISSUE THREAD

**Issue by johncblacker** [openmv/openmv-ide#162]
When I start a terminal from the IDE there is no cursor, so it's not easy to keep track of the command you're typing.  I use REPL a lot and rather than execute my script from main.py, I rename the script after uploading to the board to something like omvmain.py.  Then I can either import <myscript.py> or exec(open('myscript.py', 'r').read())  that way I'm not stuck with a non-responsive board when it gets stuck executing main.py...

**Comment by kwagyeman** [comment]
You just want the blinking standard box cursor? This is like a one like of code change for me.

**Comment by johncblacker** [comment]
Yes, that's it.  I'm surprised nobody has requested this before...

**Comment by kwagyeman** [comment]
Most people don't ever find the feature. :| I added it though because I wanted a good serial terminal.

**Comment by kwagyeman** [comment]
Done
