### ISSUE TITLE
silent install doesn't work with openmv ide v2.9.2 and v2.9.7

### ISSUE THREAD

**Issue by yjun123** [openmv/openmv-ide#164]
https://github.com/openmv/openmv-ide#instructions-for-running-the-installer-silently 

According to the above link, I cannot install openmv ide v2.9.7 and v2.9.2 silently, but works for v2.9.0.

```
$ ./openmv-ide-2.9.2-x86_64.run -platform minimal --script silent-install.qs
Unknown option: p, l, a, t, f, o, r, m
```
[silent-install.qs](https://pastebin.mozilla.org/YMe58RbX)

**Comment by kwagyeman** [comment]
Will address in the next release.

**Comment by kwagyeman** [comment]
Hi, this isn't an official feature. Also, there are some things that people mention about this issue in the link.

Anyway, I'll set this as a feature to support when I finish updating the IDE libraries to the latest Qt, Qt Creator, and Qt Installer framework.

**Comment by kwagyeman** [comment]
New Qt Installer framework for the IDE about to be released features command line install mode.

`sudo ./openmv-ide-linux-x86_64-4.0.0.run --al -c --am in`
