### ISSUE TITLE
Feature Request: Auto-reconnect after low power mode

### ISSUE THREAD

**Issue by CrispyJawa** [openmv/openmv-ide#166]
After using a command such as pyb.stop() or machine.sleep(), having the ability to reconnect to the IDE and continue making outputs to the serial terminal could be useful.

[Original forum post for additional context](https://forums.openmv.io/t/help-with-using-nicla-vision-and-low-power-mode/7741/4)

**Comment by kwagyeman** [comment]
I'll add a checkbox option to do that to the menus in the IDE.

Since this is easy it will come soon...

**Comment by kwagyeman** [comment]
Hi, the feature is implemented and working. Will come out this weekend.

There's a tool button under Tools you can just check and the IDE will do what you want.

**Comment by kwagyeman** [comment]
This feature works on the 12 Mb/s OpenMV Cams. However, on 480 Mb/s ones the OS doesn't allow the serial port object to be deleted which prevents the IDE from closing. This works after the serial port is forcibly closed by removing it from the PC.

Not sure how to fix this and it's a bug in the OS...
