### ISSUE TITLE
Typo on message box titled "Update Available" - "reources"

### ISSUE THREAD

**Issue by intGus** [openmv/openmv-ide#167]
Just a typo in OpenMV IDE 2.9.7  (**qt-creator/share/qtcreator/translations**):
**reources** instead of resources
`<message>
        <location line="+73"/>
        <source>New OpenMV IDE reources are available (e.g. examples, firmware, documentation, etc.).</source>
        <translation type="unfinished"></translation>
    </message>`

**Comment by kwagyeman** [comment]
Thanks for finding this. I fixed it. Update will be at the end of the week.
