### ISSUE TITLE
Is current openmv-ide compatible with Python 3.6.5 ?

### ISSUE THREAD

**Issue by jiapei100** [openmv/openmv-ide#17]
> fixing rpaths...
> `/media/jiapei/Data/Downloads/machinevision/openmv/openmv-ide/build/install/README.txt' probably isn't an ELF file.
> elf_open: Exec format error
> Traceback (most recent call last):
>   File "/media/jiapei/Data/Downloads/machinevision/openmv/openmv-ide/qt-creator/scripts/deployqt.py", line 339, in <module>
>     main()
>   File "/media/jiapei/Data/Downloads/machinevision/openmv/openmv-ide/qt-creator/scripts/deployqt.py", line 328, in main
>     common.fix_rpaths(install_dir, os.path.join(qt_deploy_prefix, 'lib'), qt_install_info, chrpath_bin)
>   File "/media/jiapei/Data/Downloads/machinevision/openmv/openmv-ide/qt-creator/scripts/common.py", line 165, in fix_rpaths
>     if is_unix_executable(filepath) or is_unix_library(filepath):
>   File "/media/jiapei/Data/Downloads/machinevision/openmv/openmv-ide/qt-creator/scripts/common.py", line 156, in is_unix_executable
>     return f.read(2) != "#!"
>   File "/usr/lib/python3.6/codecs.py", line 321, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 25: invalid start byte
> Makefile:569: recipe for target 'deployqt' failed
> make: *** [deployqt] Error 1
> Make Failed...
>

**Comment by jiapei100** [comment]
python 2.7 builds successfully, but failed to install?


> Files read from disk: 1099
> Archive size: 65048385 bytes (63 MiB)
> Everything is Ok
> python -u /media/jiapei/Data/Downloads/machinevision/openmv/openmv-ide/qt-creator/scripts/packageIfw.py -i "" -v 1.3.0 -a "/media/jiapei/Data/Downloads/machinevision/openmv/openmv-ide/build/openmv-ide-linux-x86_64-1.3.0-installer-archive.7z" openmv-ide-linux-x86_64-1.3.0 && python -u /media/jiapei/Data/Downloads/machinevision/openmv/openmv-ide/qt-creator/scripts/sign.py "openmv-ide-linux-x86_64-1.3.0.run"
> Traceback (most recent call last):
>   File "/media/jiapei/Data/Downloads/machinevision/openmv/openmv-ide/qt-creator/scripts/packageIfw.py", line 155, in <module>
>     main()
>   File "/media/jiapei/Data/Downloads/machinevision/openmv/openmv-ide/qt-creator/scripts/packageIfw.py", line 90, in main
>     raise Exception('Installer framework location not specified (--installer-path)!')
> Exception: Installer framework location not specified (--installer-path)!
> Makefile:578: recipe for target 'installer' failed
> make: *** [installer] Error 1
> Make Failed...
>

**Comment by kwagyeman** [comment]
You need to add install the qt installer framework on your system. This may have been the reason for the previous none type error.

**Comment by jiapei100** [comment]
@kwagyeman 
Oh, yes... I actually installed my own QT already... That might be the reason...
Anyway, I'm running **openmv** !! But, the camera is **NOT** able to be detected at all. Ubuntu 18.04 . I guess it has something to do with the hardware. My **cmucam5** is NOT working either.

**Comment by kwagyeman** [comment]
Hi, you have to install qt installer framework. Also, we don't support the CMUcam5.

Please use the binaries posted online if you'd like to use your OpenMV Cam with OpenMV IDE.
