### ISSUE TITLE
Multilingual not available in new version.

### ISSUE THREAD

**Issue by kaizhi-singtown** [openmv/openmv-ide#178]
Since the IDE was updated to 4.0.1, multilinguals are no longer available. 
Can this feature be fixed?

**Comment by kwagyeman** [comment]
What do you mean? The IDE has been translated into 32 languages.

**Comment by kaizhi-singtown** [comment]
Language selection in preference does not work.
I chose Chinese and restarted the software, but the interface is still in English.

**Comment by kwagyeman** [comment]
Is this on a Mac? Which OS?

But, yes, can fix this soon.

**Comment by kaizhi-singtown** [comment]
I tested Windows10 and MacOS, and neither worked.

**Comment by kwagyeman** [comment]
Windows should have works. Okay, will determine what is broken and fix it ASAP.

**Comment by kwagyeman** [comment]
Please let me know if the issue is fixed here: https://github.com/openmv/openmv-ide/releases/tag/development

**Comment by kwagyeman** [comment]
This seems to work now.

**Comment by kaizhi-singtown** [comment]
Yes, it works now.
