### ISSUE TITLE
Menus in OpenMV IDE are black on black text

### ISSUE THREAD

**Issue by able-archer** [openmv/openmv-ide#18]
I just installed the OpenMV IDE on a fresh Kubuntu 18.04.
I'm using the Breezy Dark theme, which is one of the 3 default themes in Kubuntu.
The IDE works fine, but the text in the menus are black on a very dark background, making it nearly impossible to read.
The menu's are fine if I choose a light theme in Kubuntu, but the dark one is easier on the eyes.

Could you create a setting to change the color of the font in the menus, or detect a darktheme usage in some way?

![ca1154a363f662f7c66349205f688b05](https://user-images.githubusercontent.com/23637709/40131941-a8d250c4-593b-11e8-8582-6954220794dc.png)

![27841e7b9a288cb406970550028c79e1](https://user-images.githubusercontent.com/23637709/40131945-aaefb41e-593b-11e8-8282-1f3e91153078.png)

**Comment by kwagyeman** [comment]
Thanks for creating a bug tracker on this. I'll try to figure out why the IDE is getting this wrong.

**Comment by kwagyeman** [comment]
I've fixed this for the next release.
