### ISSUE TITLE
Add way to trigger dataset editor to capture picture from OpenMV Cam.

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv-ide#180]
Start building out virtual command system and add this as the first command.

**Comment by iabdalkader** [comment]
This issue has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/any-way-to-add-images-captured-during-the-testing-of-my-model-to-the-dataset-itself/8783/9

**Comment by kwagyeman** [comment]
This works now. Just do:

print("\x1b[64OMV")

In your script. This executes a custom escape code sequence that will cause the IDE to save an image if possible. E.g. the same context as the button normally working.
