### ISSUE TITLE
Add support for RPI IDE to work on different versions of the OS

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv-ide#183]
Need to solve shipping the IDE will more of the required libs.

**Comment by iabdalkader** [comment]
This issue has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/openmv-ide-install-does-not-work-with-newest-raspberry-pi-os/7814/10

**Comment by kwagyeman** [comment]
Sound be fixed now using: https://github.com/openmv/openmv-ide/issues/201
