### ISSUE TITLE
Fail to open .py file in openmv-ide?

### ISSUE THREAD

**Issue by jiapei100** [openmv/openmv-ide#19]
```
$ MimeDatabase: Error loading :/qt-project.org/qmime/freedesktop.org.xml
Cannot open :/qt-project.org/qmime/freedesktop.org.xml: No such file or directory
QFSFileEngine::open: No file name specified
Gtk-Message: 02:12:34.925: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 02:13:08.435: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 02:13:16.724: GtkDialog mapped without a transient parent. This is discouraged.
static Core::EditorManager::EditorFactoryList Core::Internal::EditorManagerPrivate::findFactories(Core::Id, const QString&) unable to determine mime type of .../firsttest.py/. Falling back to text/plain
static Core::EditorManager::EditorFactoryList Core::Internal::EditorManagerPrivate::findFactories(Core::Id, const QString&): unable to find an editor factory for the file '.../firsttest.py', editor Id ''.
^C
[1]+  Done                    openmvide
```

**Comment by kwagyeman** [comment]
Can you provide the operating system? And the file? We can't exactly reproduce with that trace.

**Comment by jiapei100** [comment]
@kwagyeman 

1. OS: Ubuntu 18.04

2. OpenMV 1.9.0

About OpenMV IDE 1.9.0
By: Ibrahim Abdelkader & Kwabena W. Agyeman
GNU GENERAL PUBLIC LICENSE
Copyright (C) 2017 OpenMV, LLC
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
Questions or Comments?
Contact us at openmv@openmv.io.
Credits
OpenMV IDE English translation by Kwabena W. Agyeman.

3. Qt: 5.11.0

**Comment by kwagyeman** [comment]
Super, now the file?

**Comment by jiapei100** [comment]
Check this please ...
[http://forums.openmv.io/viewtopic.php?f=3&t=821](http://forums.openmv.io/viewtopic.php?f=3&t=821)

**Comment by kwagyeman** [comment]
Closing this.
