### ISSUE TITLE
IDE crash on cam reset

### ISSUE THREAD

**Issue by cyber-run** [openmv/openmv-ide#196]
When using Reset OpenMV Cam with the RT1062, it crashes the IDE and stops responding until it is quit and reopen. This has been confirmed with tests on multiple windows machines, with cameras running the newest firmware updated directly from the IDE.

**Comment by kwagyeman** [comment]
@cyber-run - Yes, I can confirm this if you save to Disk and then click reset. If you save to disk, disconnect, reconnect, and then click reset you do not get a crash.

I'll get this debugged soon.

**Comment by cyber-run** [comment]
sounds good thanks !

**Comment by kwagyeman** [comment]
Please leave the issue open until I fixed it.

**Comment by kwagyeman** [comment]
This issue appears to have been fixed via recent firmware updates in MicroPython.
