### ISSUE TITLE
1.x.x often crashes on OSX when clicking "disconnect"

### ISSUE THREAD

**Issue by petri** [openmv/openmv-ide#2]

**Comment by kwagyeman** [comment]
Thank's for using the software! I have a new release almost ready where I completely redid the serial code. Hopefully that will come out this weekend. When you test out the new release let me know if the problem still exists.

Yeah, again, I redid the serial code to make sure stuff like this doesn't happen. However, I've noticed that when the camera has a problem and it's USB driver crashes this causes whatever program opened the serial port to lock up to. Anyway, disconnecting the camera usually fixes this.

Until I get get Ibrahim to fix the serial library stuff like this will remain an issue. The OpenMV Cam serial code is... poor in my opinion... just really fragile.

**Comment by petri** [comment]
Still an issue on 1.1.0.

**Comment by kwagyeman** [comment]
Does this happen 100% of the time?

**Comment by petri** [comment]
I think it's worth adding a note for Mac users on the IDE download page that you only support OSX El Capitan. I did not remember I was still on OSX Yosemite. Upgraded to El Capitan overnight and seems like things are a lot more stable, including this issue.

**Comment by petri** [comment]
Seems the disconnect crash now only happens after the slow REPL (which is also followed by the start/stop button state fluctuations). So this is probably a result of either or both of those two. I bet this issue will disappear after #3 and #4 stop happening.

**Comment by kwagyeman** [comment]
Does the IDE work now? See v1.3.

**Comment by petri** [comment]
Seems to work ok now, both when there is no script running and when there is.
