### ISSUE TITLE
Use videos files instead of camera for developement

### ISSUE THREAD

**Issue by Hydrorion** [openmv/openmv-ide#20]
In order to ease tests and developpements for projects in any kind i would like to read, in the OpenMV IDE, video files from computer or/and sd card.
If it's possible it will be really great !

**Comment by jiapei100** [comment]
Same question here....

**Comment by kwagyeman** [comment]
It's on the todo list.

**Comment by kwagyeman** [comment]
This is now fixed. The IDE will be able to convert video files to the ImageWriter file format so you can pull from that.
