### ISSUE TITLE
make target 'installer' error

### ISSUE THREAD

**Issue by tiangaomingjing** [openmv/openmv-ide#23]
make: Leaving directory '/home/chao/Git/openmv-ide/build'
make: *** No rule to make target 'installer'。 stop.
Make Failed...

who can tell me why?? 
./make.py

**Comment by tiangaomingjing** [comment]
yeah, I have installed the QtInstallerFramework3.0.2 and Qt5.10.0 ,in the /build ,the qtcreator is builded successfully .  But I cannot find OpenMV plugins.   
the error occur maybe here :
" && make installer INSTALL_ROOT="+installdir + " IFW_PATH="+ifdir):
            sys.exit("Make Failed...")"

**Comment by kwagyeman** [comment]
Closing this.
