### ISSUE TITLE
qt-creator pull request?

### ISSUE THREAD

**Issue by jiapei100** [openmv/openmv-ide#25]
It looks openmv-ide and qtcreator are of two different git repos?
Anyway, I cannot pull request directly from openmv-ide directory, for some modifications are made under subfolder: qt-creator.

```
- /src/plugins/coreplugin/dialogs/readonlyfilesdialog.cpp
+#include <QButtonGroup>

- /src/plugins/coreplugin/find/findtoolbar.cpp
+#include <QAbstractItemView>
```

- scripts/deployqt.py
For **ALL print**, add parenthesis ()

etc...

**Comment by kwagyeman** [comment]
I don't understand this error.

**Comment by jiapei100** [comment]
@kwagyeman 

I mean, when I tried to compile **openmv-ide** from source with **python3**, I got some **ERROR** messages. So, the above 3 points are partial solutions...

**Comment by kwagyeman** [comment]
Hi, you would have to create a fork of both repos and then submit a PR for each.
