### ISSUE TITLE
Ubuntu OpenMV IDE can not input Chinese

### ISSUE THREAD

**Issue by kaizhi-singtown** [openmv/openmv-ide#32]
May be a problem with textarea, I can't input Chinese with Pinyin. I can type Chinese in other applications like firefox.
There are no problems on both Windows and Mac OS.

OpenMV IDE version: 2.1.0
Ubuntu version: 18.04.1 LTS

![c2b3bfc5d9ff991bd3188efafe6122cc](https://user-images.githubusercontent.com/9582040/51974505-056ca000-24bb-11e9-8cc6-73e3a33a98c5.jpg)

**Comment by kaizhi-singtown** [comment]
Yes, I can copy and paste Chinese.
![image](https://user-images.githubusercontent.com/9582040/52029417-10bcdb80-254e-11e9-881c-9169f6e6cf56.png)
Normally, when I type Pinyin, the box for this word selection will appear. But the OpenMV IDE in Ubuntu won't.

**Comment by kwagyeman** [comment]
Can you check if this is the problem?

https://bugs.launchpad.net/ubuntu-sdk-ide/+bug/1534492

Or this?

http://blog.kroody.org/2016/01/cant-type-chinese-in-qt5qtcreator-using-fcitx/

?

https://www.google.com/search?q=qt+creator+cannot+input+chinese+in+ubuntu&spell=1&sa=X&ved=0ahUKEwiwp_GCvcfhAhX9HTQIHQSMA7AQBQgrKAA&biw=1200&bih=1974

**Comment by kwagyeman** [comment]
I don't know how to solve this issue. Just submit a PR for whatever commands need to be executed to fix the issue here:

https://github.com/openmv/openmv-ide/blob/master/make.py#L216

**Comment by kwagyeman** [comment]
Add them after this line: https://github.com/openmv/openmv-ide/blob/master/make.py#L221
