### ISSUE TITLE
make.py feature

### ISSUE THREAD

**Issue by bogflap** [openmv/openmv-ide#39]
At present make.py for linux (Opensuse in fact) searches for a directory Qt in the home directory.
Unfortunately I have a directory called QtCreatorWorkspace in my home directory which make.py finds as qtdir.
I am not that familiar enough with python to suggest a fix but perhaps searching for directory "Qt" only might help

**Comment by kwagyeman** [comment]
Here?

https://github.com/openmv/openmv-ide/blob/master/make.py#L84

**Comment by bogflap** [comment]
Yes, line 104

**Comment by kwagyeman** [comment]
Just change the "Qt" string to "^Qt$" here:

https://github.com/openmv/openmv-ide/blob/master/make.py#L44

and 

https://github.com/openmv/openmv-ide/blob/master/make.py#L104

This forces the match to be on a string that just says Qt versus the first characters of it.

**Comment by bogflap** [comment]
Okay
