### ISSUE TITLE
Suggestion: Firmware Upgrade Complete Dialogue Text Re-Wording

### ISSUE THREAD

**Issue by Luxonis-Brandon** [openmv/openmv-ide#40]
![image](https://user-images.githubusercontent.com/32992551/55817870-a034bc80-5ab2-11e9-9dc2-96e5055a17df.png)
This is not a big deal... but it wasn't abundantly clear if one should wait -until- the blue LED starts blinking or -after- it stops blinking.  

By the time I noticed the dialogue, the LED was already blinking blue, which contributed to the ambiguity.

Anyways, here's the existing text:
```
Done upgrading your OpenMV Cam's firmware!


Click the Ok button after your OpenMV Cam has enumerated and finished running its built-in self test (blue led blinking - this takes a while).
```
And here's a cut at suggested:
```
Upgrade complete.

Your OpenMV Cam is running its built-in self-test… this may take a while.

Click OK when the OpenMV blinks blue - which indicates self-test complete.
```

**Comment by kwagyeman** [comment]
Changed
