### ISSUE TITLE
Suggestion: Highlight Available Examples

### ISSUE THREAD

**Issue by Luxonis-Brandon** [openmv/openmv-ide#41]
There are a plethora of excellent examples.  Would be neat on first-install to highlight these so that users don't miss them tucked away in File > Examples.

And ideally, it would be neat to have an examples window view where you can browse through them and select/run w/out having to go to File > Example > and scroll through the list each time.

![image](https://user-images.githubusercontent.com/32992551/55818485-f48c6c00-5ab3-11e9-9fbb-d03d283a2d0a.png)

**Comment by kwagyeman** [comment]
Will do first request.
