### ISSUE TITLE
Translation Problems

### ISSUE THREAD

**Issue by Hofer-Julian** [openmv/openmv-ide#43]
When I first connected our openmv cam I got a cryptical message. Only after I changed the language from German to English I saw that I should execute "sudo adduser...". Maybe the code could be changed so that this line does not get translated?

**Comment by kwagyeman** [comment]
Hi, it must have been translated by our bulk translation service. Could you post the message here? I'll get it fixed in the next IDE release.

**Comment by Hofer-Julian** [comment]
@kwagyeman not sure if I can reproduce it.

I probably would need to remove to user from the group again, right?

**Comment by kwagyeman** [comment]
German translations are here if you want to search for it.

https://github.com/openmv/qt-creator/blob/b587ed9f6c93c6844782dc2e54c307878419c8e1/share/qtcreator/translations/qtcreator_de.po

**Comment by Hofer-Julian** [comment]
It is this part in https://github.com/openmv/qt-creator/blob/b587ed9f6c93c6844782dc2e54c307878419c8e1/share/qtcreator/translations/qtcreator_de.po#L8487:

```
#: ../../../src/plugins/openmv/openmvplugin.cpp:1808
msgctxt "OpenMV::Internal::OpenMVPlugin|"
msgid ""
"\n"
"\n"
"Try doing:\n"
"\n"
"sudo adduser %L1 dialout\n"
"\n"
"...in a terminal and then restart your computer."
msgstr ""
"\n"
"\n"
"Versuchen Sie Folgendes:\n"
"\n"
"Übernehmen Sie User %L1 Dialout\n"
"\n"
" ... in einem Terminal und starten Sie Ihren Computer neu."
```

"Übernehmen Sie User %L1 Dialout\n" should be changed  to ""sudo adduser %L1 dialout\n". Maybe you could make it so that this problem doesn't occur for other languages as well

**Comment by kwagyeman** [comment]
I think the beat I can do it to make sure the command text is not in the translation string. Then Google won't translate it.

**Comment by Hofer-Julian** [comment]
@kwagyeman that's what I wanted to suggest :)

**Comment by kwagyeman** [comment]
Fixed
