### ISSUE TITLE
Add a note that the camera is fine if the blue light is blinking

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv-ide#46]
But tell the user that their USB cable might be power only and that they should get a verified USB cable that does data too.

**Comment by jideshv** [comment]
This happened after using a case for me. The USB cable I was using had slightly shorter data pins and after putting the camera in the case it no longer connected.

**Comment by kwagyeman** [comment]
Fixed, added some messages to the IDE to let users know.
