### ISSUE TITLE
Camera crashes if IDE overwrites the running script (1.x.x on OSX El Capitan)

### ISSUE THREAD

**Issue by petri** [openmv/openmv-ide#5]
Steps to reproduce:
1. connect camera
2. start a script
3. while the script is still running, overwrite the (running) script (via IDE) on camera.

There will usually be different errors, apparently depending on the actual changes to the script. The only way to recover is to physically disconnect-reconnect the USB.

The crash does not always happen - it seems the more there are changes to the script, the higher the likelihood of crash.

I would suggest disabling the save button while the script runs.

**Comment by kwagyeman** [comment]
Got a new version coming soon. But, um, which save script button? The save script to the computer or camera?

I'm pretty sure you're having all these issues because of the serial driver crashing because of the way the OpenMV Camera firmware works. I'm hopping the the upcoming switch to 64-byte packets in the IDE will fix this.

**Comment by petri** [comment]
Ok. I meant overwrite of a script stored on (and running from) the SD card attached to the camera.

**Comment by kwagyeman** [comment]
Sounds like a firmware issue.

Can you post this issue in the openmv repo? There's nothing sepcial going on in the IDE to update the script while running. It's just saving a file to the SD card using the USB flash drive access.

**Comment by kwagyeman** [comment]
Oh, so, I got busy with business stuff this weekend. Wasn't able to finish the IDE updates. Hopefully I can get back to that tomorrow.

**Comment by kwagyeman** [comment]
Does the IDE work now? See v1.3.

**Comment by petri** [comment]
With 1.3, the following now happens on OSX El Capitan:
- when using the special Tools -> "save open script to OpenMV cam" menu item from the IDE, nothing happens; it seems the IDE refuses to save the script
- when instead attempting to save the script via the File -> Save menu item in IDE, the IDE pops up an error message (OSError; Assertion failed or OSError; unsupported format), and the script execution stops gracefully

**Comment by kwagyeman** [comment]
Hi, can you close this issue and open up for the OpenMV repo as a firmware issue? I can't do anything other than disable the ability to save a script while one is running in the IDE. However, it sounds like the cam should be able to handle this situation.
