### ISSUE TITLE
IDE should append .py on script filename

### ISSUE THREAD

**Issue by OttawaMaker** [openmv/openmv-ide#50]
### Steps to reproduce
1. Save a script
2. Enter a filename
3. Notice that .py is not automatically appended to the filename

### Expected behaviour
Tell us what should happen

### Actual behaviour
Script saved with no file extension

### Describe your setup

**IDE version:**
2.2.0
**Firmware version:**

**Operating system:**
Windows 7, 10
### For developers

**GCC version:**

**Build target:**

**Comment by kwagyeman** [comment]
The IDE can edit any files. It adds the .py part to any file it creates and new files you make in it. If you choose to remove the .py extension that's allowed. The OpenMV Cam doesn't care what the extension is so you can remove that part if you like.
