### ISSUE TITLE
Fix/update the debugging protocol.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv-ide#58]
The USB debugging protocol needs to be more consistent with how it deals with payloads. Currently all commands set the length of the payload and then send the payload in a separate packet, except for 3 commands (read_attr, write_atrr and enable_fb) which set the length to 0 and send the payload in the same packet. I suggest we fix this so that all the commands are the same i.e. 6 bytes header in one packet and then payload (if any) in separate packet(s). The only drawback this may break older firmware so maybe force a firmware update after fixing this.

**Comment by kwagyeman** [comment]
Donne. The IDE will break up the command and data phases for fbenable, jpegenable (not actually sent anymore but the code has been maintained), getattr, and setsttr. Firmware 3.5.3 and above turns this on.
