### ISSUE TITLE
Why OpenVM comes with qt-creator?

### ISSUE THREAD

**Issue by jiapei100** [openmv/openmv-ide#7]
This is more or less unreasonable...
qt-creator is a part of Qt ...

Any plan remove qt-creator ane make OpenMV much clearer?
Can we just build OpenVM purely, and stick to looking on qt-creator as an independent installation ?

Cheers
Pei

**Comment by kwagyeman** [comment]
Hi, The OpenMV IDE is built on top of qtcreator. I just made a plugin that adds the functionality that I wanted and then tweaked all the code in QtCreator that I needed to do.

Please understand. It's not like you can decouple the two parts. It's not even like you're getting qtcreator in the first place. I've removed more or less 90% of qtcreator's functionality to just get the text editor and main window part.

Anyway, please ask questions about the OpenMV project via email.

Thanks,

(If you are complaining about the IDE install size it's really no bigger than Arduino's install size currently).
