### ISSUE TITLE
Line Break Issues in LED Messages

### ISSUE THREAD

**Issue by MiWeiss** [openmv/openmv-ide#75]
The following message (shown on startup - German version) has some problems showing the line breaks `\n\n`.

![image](https://user-images.githubusercontent.com/4815944/80727416-fb927c00-8b05-11ea-915d-f1bab2390a64.png)

Windows10
OpenMV IDE 2.4.0

Clearly a very low priority issue, but I thought you might want to know.

**Comment by MiWeiss** [comment]
Note: English version looks good: 

![image](https://user-images.githubusercontent.com/4815944/80727943-a4d97200-8b06-11ea-837a-c5c2bb033b40.png)

**Comment by kwagyeman** [comment]
Will fix!

**Comment by kwagyeman** [comment]
Fixed
