### ISSUE TITLE
IDE Support for WiFi Connections

### ISSUE THREAD

**Issue by askpatrickw** [openmv/openmv-ide#77]
If your OPENMV is set to connect to your the same WIFI as the computer you're running OpenMV IDE on, you will see connect button (lower-left) allow you to connect over WiFi to your OpenMV Camera. This is not yet full supported, but coming soon according to this thread:
https://forums.openmv.io/viewtopic.php?f=6&t=1854&p=11168#p11168

I spent a few hours trying to figure out why this wasn't working. Hope this helps others.

**Comment by kwagyeman** [comment]
Yes, it's not functional as of right now.

**Comment by kwagyeman** [comment]
We got this working now! Coming next release.
