### ISSUE TITLE
Video converter doesn't add the extension.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv-ide#89]
The video converter doesn't add the file extension for the format selected from the drop-down menu, and it has to be provided manually. Also please check if it is provided to avoid adding it twice.

**Comment by kwagyeman** [comment]
https://bugreports.qt.io/browse/QTBUG-27186?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true

I've put some code to cause a retry to happen if the extension is missing.
