### ISSUE TITLE
qtcreator.pro missing

### ISSUE THREAD

**Issue by deshipu** [openmv/openmv-ide#9]
I'm trying to build this, I figured out where to put all the deps, but now when I run `make.py` I get:

```
$ python make.py 
Cannot find file: ../qt-creator/qtcreator.pro.
Make Failed...
```

It seems that file is missing from the repository.

**Comment by kwagyeman** [comment]
You need to install the qtcreator sub repo. You have to init the submodule.

**Comment by deshipu** [comment]
Ah, I see, thanks!

**Comment by kwagyeman** [comment]
Also make sure to checkout the openmv branch of the submodule. Not sure why git doesn't see this. It's in the submodule spec file.

**Comment by kwagyeman** [comment]
Um, one more thing. Don't use the make.py script. That's for release. Just load the qtcreator.pro file directly in QtCreator and it will create the build dir, etc. for you and you can start hacking.

**Comment by deshipu** [comment]
Excellent, thanks!

**Comment by deshipu** [comment]
Hmm, I'm getting ":-1: error: Unknown module(s) in QT: qml" both in qtcreator and with make.py, and I'm not sure what I need to install -- there are 100s of packages with "qml" in their name...

**Comment by kwagyeman** [comment]
Um, qml shouldn't be showing up.  Pretty sure I unlinked that. You might have installed the qml submodule in qtcretor. You don't want that. Just destroy the repo for that in the qctcreator repo.

**Comment by kwagyeman** [comment]
Once the repo for that is destroyed then the build script shouldn't pick it up. (the qtcreator.pro file that is).

**Comment by deshipu** [comment]
Not sure what you mean here. How do I destroy that repo?

**Comment by kwagyeman** [comment]
Just delete the dir that gets inited from the qtcreator .submodule file.

**Comment by kwagyeman** [comment]
https://github.com/openmv/qt-creator/blob/1793b0b5cdec2d929e3140ba628cf8124fa12143/.gitmodules

**Comment by kwagyeman** [comment]
src/shared/qbs

**Comment by deshipu** [comment]
Now I get: :-1: error: Unknown module(s) in QT: help, and deleting src/shared/help didn't help.

**Comment by kwagyeman** [comment]
You only wanted to delete qbs. Um, how did you install Qt?

**Comment by deshipu** [comment]
apt-get install qtcreator

**Comment by kwagyeman** [comment]
Oh, yeah, don't use that.  Install the SDk from qt online. Or, also do "apt-get install qt".

QtCreator contains all the tools to build Qt code but not any of the libraries.

I'd just install everything from this: https://www.qt.io/download-open-source/

**Comment by deshipu** [comment]
E: Unable to locate package qt

I'd rather not install non-packaged stuff on my system. I guess I will need a virtual machine for this.

Thank you for your help.

**Comment by kwagyeman** [comment]
Oh, no, it's safe to do. The qt installer just unpacks everything to your home dir. It doesn't modify any paths or anything. If you want to remove it you just have to delete the install dir (they have an uninstaller too).

Anyway, what are you trying to do?

**Comment by kwagyeman** [comment]
https://wiki.qt.io/Install_Qt_5_on_Ubuntu

**Comment by deshipu** [comment]
I'm presenting a talk about MicroPython on a conference on Friday, and I wanted to also show OpenMV there -- for that, I wanted to see how the newest version of the IDE works.

**Comment by kwagyeman** [comment]
Okay, uh, but, why do you need to build it versus just showing off the code?

**Comment by deshipu** [comment]
I just wanted to run the most recent version.

**Comment by kwagyeman** [comment]
Oh, well, the only changes I made were to add AprilTag generating code from what has been released. You don't have an M7 cam so you can't use that just yet. Anyway, I can make a quick build for you if you like. Otherwise, you'll need to install Qt on your system.

**Comment by kwagyeman** [comment]
(And yes, I understand how much building the IDE is a pain. Trust me that for actually building the release versions I had to go through even more pain since you have to build them on Ubuntu 12).

**Comment by deshipu** [comment]
I actually wanted to do it now, so that I can also follow the development as it happens and see what you are working on, without having to wait for releases. Of course, this is not important, and I can as well just show the released version at the talk (in fact, I probably should, as it will be less likely to crash). I guess it's just the open source habits.

**Comment by kwagyeman** [comment]
Okay, well, follow the link I posted above to build on linux then. For just developing you don't have to do anything more than that.

**Comment by deshipu** [comment]
Thanks again!

**Comment by kwagyeman** [comment]
Oh, BTW. I finally have time to fix the syntax highlighting and autocomplete. I'd working on that next. The next release of the IDE should be the first one with no obvious unfinished parts.

**Comment by deshipu** [comment]
Great to hear. It's amazing how much work you are putting into this. Makes me feel guilty for not finishing that hexapod robot with openmv on it. But it's not abandoned, just shelved...
