### ISSUE TITLE
Installer won't update existing installation

### ISSUE THREAD

**Issue by frank26080115** [openmv/openmv-ide#95]
Windows 10, upgrading IDE to v2.6.5

The installer won't let me upgrade over an existing installation of OpenMV IDE

**Comment by kwagyeman** [comment]
Delete the current installation and then install the new one. The installer frame work we use from at won’t let us update in place.

**Comment by frank26080115** [comment]
maybe use fileExists() and setUpdater() in the script? or offer to call the uninstaller if fileExists() returns true?

**Comment by kwagyeman** [comment]
I think in later versions of the tool they fixed this. I just haven’t made it a serious priority to fix.

I’ll leave it as a bug, then take a look for the next release.

**Comment by falthaus** [comment]
On Win10, upgrading from IDE v2.8.1 to v2.9.0, the old version again has to be deinstalled manually first (same behaviour on two different Win10 machines).
It's a while since v2.8.1 came out, but I thought this used to be fixed(?)

**Comment by kwagyeman** [comment]
Yeah, I haven't fixed it yet.

We will be fixing it in the next release. I will be upgrading the Qt Version and Qt Installer framework version. This will also result in a loss of support for 32-bit systems. Newer versions of Qt only support 64-bit.

(This is hard to fix at our current framework version as there's no support and which is several years old right now to keep 32-bit support working).

**Comment by kwagyeman** [comment]
Fixed
