### ISSUE TITLE
Context menu entries not readable on macOS

### ISSUE THREAD

**Issue by sebromero** [openmv/openmv-ide#96]
The context menu has white text on bright background so the text is only visible on hover.

![image](https://user-images.githubusercontent.com/1326220/96845980-9a62ba00-1451-11eb-9dca-02e088749d4f.png)

**Comment by kwagyeman** [comment]
I think I fixed this with an update of the Qt Library on Mac for the next release.

**Comment by kwagyeman** [comment]
Found the issue and fixed it. Actually, I broke this long ago. I guess it was a fix for other operating systems.
