### ISSUE TITLE
Simplify DFU firmware installation dialog

### ISSUE THREAD

**Issue by sebromero** [openmv/openmv-ide#97]
The current version of the dialog window that appears when connecting a board in DFU mode is a tad information heavy. I'd suggest to focus on the primary call to action and "hide" the "advanced" options in a dropdown menu. -> See mockup below

Also I don't fully understand the difference between "Erase Onboard Data Flash" and "Erase the internal file system?". Is it the same? In any case, I'd suggest making this an option of the dialog window and adding a tooltip or a label explaining what this option does.

<img width="1042" alt="Screenshot 2020-09-22 at 09 21 13" src="https://user-images.githubusercontent.com/1326220/97896410-5024e700-1d35-11eb-8c44-279545a67fe5.png">
<img width="441" alt="Screenshot 2020-09-22 at 09 21 45" src="https://user-images.githubusercontent.com/1326220/97897009-2c15d580-1d36-11eb-8656-27921d873f6a.png">

**Mockup**
![image](https://user-images.githubusercontent.com/1326220/97897489-da217f80-1d36-11eb-9eb0-fc1c80a7ccdf.png)

**Comment by kwagyeman** [comment]
Hi, I can partially do this easily. Please understand that the way to program the board is through the bootloader. Because we have to support Arduino's different DFU bootloader this is unnecessarily compilated.

I'll simply this menu and add some help some more text strings.

**Comment by kwagyeman** [comment]
Fixed in next release.
