### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv-ide#98]
Add option to switch between light and dark mode.

**Comment by baljo** [comment]
Hi, any ETA on this one? If implemented in next release, I'd buy you a cup of coffee/tea :-)
BTW, I am the one asking for it in the forums.

**Comment by kwagyeman** [comment]
It's like very hard. Reskinning the whole IDE is not trivial.

**Comment by kwagyeman** [comment]
The ETA for this is pretty much infinite without external help.

**Comment by dewhisna** [comment]
Actually, it might be more trivial than you think.  Being Qt Creator based, you should be able to just load a new style sheet when you launch it, which is just a command-line option. Here's one that's available: [https://draculatheme.com/qtcreator/](https://draculatheme.com/qtcreator/)

**Comment by kwagyeman** [comment]
Sorry, the current mode is dark mode. What you guys want is light mode.

A lot of the widgets are custom styled by me. They aren't done so through QtCreator. So, I'll have to add this option and then fix styling for one widget after another. This is probably 20+ hours of work.

As I have to focus on drivers like triple buffering for the camera I don't really have time.

**Comment by kwagyeman** [comment]
If you want it done convince Arduino folks it needs to be done. Then I can get contracting hours for it.

**Comment by baljo** [comment]
Hmm, a pity, I believe there are as many who loves dark modes as who cannot stand them for different reasons. My reason are simple practical, not based on feelings. I can't use dark mode at all as I need to turn up the brightness too much which kills my eyes, latest when switching to another application.

**Comment by kwagyeman** [comment]
No, I understand dark mode has issues. In particular, it's quite a challenge to use outside in sunlight.

Okay, so, this is easy to do... I can allow the editor style to change to a different mode. This will look uglyish, but, change 70% of the application to light mode.

**Comment by baljo** [comment]
> No, I understand dark mode has issues. In particular, it's quite a challenge to use outside in sunlight.
> 
> Okay, so, this is easy to do... I can allow the editor style to change to a different mode. This will look uglyish, but, change 70% of the application to light mode.

Awesome! If needed, I'd be happy to test it when (not if :-) ) you have it ready and give feedback!

**Comment by baljo** [comment]
Any hope to have option of light mode in next IDE-version?

**Comment by kwagyeman** [comment]
Nope, however, tabs, split view, and minimap in the scroll bar will come.

For light mode to happen I honestly need help.

**Comment by baljo** [comment]
Ok, unfortunately I don't have the knowledge or capacity to help myself. Am though willing to test when the time comes.

**Comment by baljo** [comment]
Now when you're upgrading Qt libraries, any chance of getting a light mode option?

**Comment by kwagyeman** [comment]
Yeah, Qt 6.5 which will be updating to has this feature. So, it will be across the board.

**Comment by baljo** [comment]
Great news, at least for me!

**Comment by kwagyeman** [comment]
This is fixed for version 4.0.0. Light mode will also land too. The whole IDE is themed now so it can be whatever color you like.
