### ISSUE TITLE
Label in "connecting" dialog gets cut off on macOS

### ISSUE THREAD

**Issue by sebromero** [openmv/openmv-ide#99]
I'm using version 2.6.6
<img width="381" alt="Screenshot 2020-11-03 at 09 26 34" src="https://user-images.githubusercontent.com/1326220/98006254-4dd49280-1df2-11eb-84f7-7e48e7f87b81.png">

**Comment by kwagyeman** [comment]
Will add a new line.

**Comment by kwagyeman** [comment]
-> "Connecting...\n\n(Hit cancel if this takes more than 5 seconds)."
